language: go
go:
  - "1.10"
before_script:
  - go get github.com/akavel/rsrc
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - go run manifest-generator/main.go $(git describe)
      - curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
