language: go
go:
  - "1.10"
before_script:
  - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
  - go run compiler/main.go $(git describe)
deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: dist/*
    on:
      tags: true
