language: go
go:
  - "1.10"
before_script: go get github.com/akavel/rsrc
script: go run compiler/compiler.go
deploy:
  provider: releases
  api_key: $KEY
  skip_cleanup: true
  file_glob: true
  file: dist/**/*
  on:
    tags: true