language: go
go: "1.11"

script:
  - cd compiler
  - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
  - cd ..
  - go run compiler/main.go $(git describe)
  - ./update_tap.sh $TAP_TOKEN

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
